// Auth
export const AUTH_START_EMAIL = "AUTH_START_EMAIL";
export const AUTH_START_GOOGLE = "AUTH_START_GOOGLE";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const RECOVERY_START = "RECOVERY_START";
export const RECOVERY_SUCCESS = "RECOVERY_SUCCESS";
export const RECOVERY_FAIL = "RECOVERY_FAIL";

export const CLEAN_UP = "CLEAN_UP";

export const CLOSE_SIDE_DRAWER = "CLOSE_SIDE_DRAWER";
export const OPEN_SIDE_DRAWER = "OPEN_SIDE_DRAWER";

export const VERIFY_START = "VERIFY_START";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";
export const VERIFY_FAIL = "VERIFY_FAIL";

export const PROFILE_EDIT_START = "PROFILE_EDIT_START";
export const PROFILE_EDIT_SUCCESS = "PROFILE_EDIT_SUCCESS";
export const PROFILE_EDIT_FAIL = "PROFILE_EDIT_FAIL";

export const SET_SORT_VIEW = "SET_SORT_VIEW";
export const SET_FILTER_VIEW = "SET_FILTER_VIEW";

export const LOGOUT_CLEAN_UP = "LOGOUT_CLEAN_UP"

// Tasks
export const ADD_TASKS_LIST_START = "ADD_TASKS_LIST_START";
export const ADD_TASKS_LIST_SUCCESS = "ADD_TASKS_LIST_SUCCESS";
export const ADD_TASKS_LIST_FAIL = "ADD_TASKS_LIST_FAIL";

export const EDIT_TASKS_LIST_START = "EDIT_TASKS_LIST_START";
export const EDIT_TASKS_LIST_SUCCESS = "EDIT_TASKS_LIST_SUCCESS";
export const EDIT_TASKS_LIST_FAIL = "EDIT_TASKS_LIST_FAIL";

export const DELETE_TASKS_LIST_START = "DELETE_TASKS_LIST_START";
export const DELETE_TASKS_LIST_SUCCESS = "DELETE_TASKS_LIST_SUCCESS";
export const DELETE_TASKS_LIST_FAIL = "DELETE_TASKS_LIST_FAIL";

export const ADD_TASK_START = "ADD_TASK_START";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FAIL = "ADD_TASK_FAIL";

export const EDIT_TASK_START = "EDIT_TASK_START";
export const EDIT_TASK_SUCCESS = "EDIT_TASK_SUCCESS";
export const EDIT_TASK_FAIL = "EDIT_TASK_FAIL";

export const DELETE_TASK_START = "DELETE_TASK_START";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_FAIL = "DELETE_TASK_FAIL";

export const DELETE_ALL_TASKS_START = "DELETE_ALL_TASKS_START";
export const DELETE_ALL_TASKS_SUCCESS = "DELETE_ALL_TASKS_SUCCESS";
export const DELETE_ALL_TASKS_FAIL = "DELETE_ALL_TASKS_FAIL";

// export const GET_TASK_ITEMS_START = "GET_TASK_ITEMS_START";
// export const GET_TASK_ITEMS_SUCCESS = "GET_TASK_ITEMS_SUCCESS";
// export const GET_TASK_ITEMS_FAILURE = "GET_TASK_ITEMS_FAILURE";

export const SELECT_TASK_LIST = "SELECT_TASK_LIST";
export const GET_TASK_LISTS = "GET_TASK_LISTS";
export const GET_TASK_ITEMS = "GET_TASK_ITEMS";

// Friends
export const ADD_FRIEND_START = "ADD_FRIEND_START";
export const ADD_FRIEND_SUCCESS = "ADD_FRIEND_SUCCESS";
export const ADD_FRIEND_FAIL = "ADD_FRIEND_FAIL";

export const ACCEPT_FRIEND_START = "ACCEPT_FRIEND_START";
export const ACCEPT_FRIEND_SUCCESS = "AACCEPT_FRIEND_SUCCESS";
export const ACCEPT_FRIEND_FAIL = "ACCEPT_FRIEND_FAIL";

export const DELETE_FRIEND_START = "DELETE_FRIEND_START";
export const DELETE_FRIEND_SUCCESS = "DELETE_FRIEND_SUCCESS";
export const DELETE_FRIEND_FAIL = "DELETE_FRIEND_FAIL";

export const SHARE_TASKS_LIST_START = "SHARE_TASKS_LIST_START";
export const SHARE_TASKS_LIST_SUCCESS = "SHARE_TASKS_LIST_SUCCESS";
export const SHARE_TASKS_LIST_FAIL = "SHARE_TASKS_LIST_FAIL";

export const UNSHARE_TASKS_LIST_START = "UNSHARE__TASKSLIST_START";
export const UNSHARE_TASKS_LIST_SUCCESS = "UNSHARE_TASKS_LIST_SUCCESS";
export const UNSHARE_TASKS_LIST_FAIL = "UNSHARE_TASKS_LIST_FAIL";